#!/usr/bin/env node
/**
 * fetch-stocks.cjs
 * Fetches 12-month monthly price history + current quote for the 4 OTA peers
 * from Yahoo Finance and writes public/stock-data.js for the dashboard.
 *
 * Node.js has no CORS restrictions, so Yahoo Finance API works here even though
 * it would be blocked in the browser.
 *
 * Run automatically by refresh-and-deploy.sh alongside fetch-news.cjs.
 */

const axios = require('axios');
const fs    = require('fs');
const path  = require('path');

const TICKERS = ['ABNB', 'BKNG', 'EXPE', 'TCOM'];
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

// ── Yahoo Finance auth: get a crumb + session cookie ────────────────────────
async function getYahooCrumb() {
  const res = await axios.get('https://fc.yahoo.com/', {
    headers: { 'User-Agent': UA },
    timeout: 10000,
    validateStatus: () => true,
  });
  const crumb   = typeof res.data === 'string' ? res.data.trim() : '';
  const cookies = (res.headers['set-cookie'] || []).join('; ');
  return { crumb, cookies };
}

// ── Fetch 1-year monthly chart for a single ticker ──────────────────────────
async function fetchChart(ticker, crumb, cookies) {
  const qs = new URLSearchParams({
    range:          '1y',
    interval:       '1mo',
    includePrePost: 'false',
    events:         'history',
    ...(crumb ? { crumb } : {}),
  });
  const url = `https://query2.finance.yahoo.com/v8/finance/chart/${ticker}?${qs}`;
  const res = await axios.get(url, {
    headers: { 'User-Agent': UA, 'Cookie': cookies, 'Accept': 'application/json' },
    timeout: 15000,
  });
  if (res.data?.chart?.error) throw new Error(res.data.chart.error.description);
  return res.data.chart.result[0];
}

// ── Parse a chart result into the shape the dashboard expects ───────────────
function parseResult(result) {
  const meta       = result.meta;
  const timestamps = result.timestamp || [];
  const rawCloses  = result.indicators?.quote?.[0]?.close || [];

  // Forward-fill nulls (Yahoo sometimes returns null for incomplete months)
  const closes = [];
  for (const v of rawCloses) {
    closes.push(v != null ? v : (closes.length ? closes[closes.length - 1] : null));
  }

  const labels = timestamps.map(ts => {
    const d = new Date(ts * 1000);
    return d.toLocaleDateString('en-US', { month: 'short', year: '2-digit' });
  });

  const currentPrice = meta.regularMarketPrice ?? closes[closes.length - 1];
  const startPrice   = closes[0];

  // YTD: find the last Dec close (or first available this year)
  const now = new Date();
  let ytdStart = startPrice;
  for (let i = 0; i < timestamps.length; i++) {
    const d = new Date(timestamps[i] * 1000);
    if (d.getFullYear() === now.getFullYear() && d.getMonth() === 0) {
      ytdStart = closes[i];
      break;
    }
    if (d.getFullYear() < now.getFullYear()) {
      ytdStart = closes[i]; // keep updating — last Dec close before this year
    }
  }

  const ytdPct  = ytdStart  ? +((currentPrice - ytdStart)  / ytdStart  * 100).toFixed(1) : null;
  const oneYPct = startPrice ? +((currentPrice - startPrice) / startPrice * 100).toFixed(1) : null;

  return {
    ticker:       meta.symbol,
    price:        +currentPrice.toFixed(2),
    marketCap:    meta.marketCap   ?? null,
    trailingPE:   meta.trailingPE  ?? null,
    ytdPct,
    oneYPct,
    currency:     meta.currency || 'USD',
    labels,
    closes:       closes.map(v => v != null ? +v.toFixed(2) : null),
    asOf:         new Date().toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric' }),
  };
}

async function main() {
  console.log('📈 Fetching stock data...');

  let crumb = '', cookies = '';
  try {
    ({ crumb, cookies } = await getYahooCrumb());
  } catch (e) {
    console.log('  ⚠  Could not get Yahoo crumb — trying without auth');
  }

  const results = {};
  for (const ticker of TICKERS) {
    process.stdout.write(`  ${ticker}... `);
    try {
      const raw = await fetchChart(ticker, crumb, cookies);
      results[ticker.toLowerCase()] = parseResult(raw);
      console.log(`$${results[ticker.toLowerCase()].price} (${results[ticker.toLowerCase()].oneYPct > 0 ? '+' : ''}${results[ticker.toLowerCase()].oneYPct}% 1Y)`);
    } catch (e) {
      console.log(`⚠  ${e.message}`);
      results[ticker.toLowerCase()] = null;
    }
  }

  const generated = new Date().toLocaleString('en-US', {
    month:'short', day:'numeric', year:'numeric',
    hour:'numeric', minute:'2-digit', timeZoneName:'short',
  });

  const outPath = path.join(__dirname, '../public/stock-data.js');
  fs.writeFileSync(outPath,
    `// Auto-generated by scripts/fetch-stocks.cjs — ${generated}\n` +
    `window.OTA_STOCK_DATA      = ${JSON.stringify(results, null, 2)};\n` +
    `window.OTA_STOCK_GENERATED = "${generated}";\n`,
    'utf8',
  );

  const ok = Object.values(results).filter(Boolean).length;
  console.log(`\n✅ ${ok}/${TICKERS.length} tickers fetched · ${generated}`);
}

main().catch(e => { console.error(e); process.exit(1); });
